<?php
/*
 * @category    Tandym
 * @package     Tandym_Tandympay
 * @copyright   Copyright (c) Tandym (https://www.bytandym.com/)
 */
?>
<?php
use Tandym\Tandympay\Block\Widget\PDP;
/** @var $block PDP */
?>



<?php if ($block->isWidgetEnabledForPDP()) {?>
<?php 
$itemPrice = $block->getItemPrice() * 100;
$publicKey = $block->getPublicKey();
$paymentMode = $block->getPaymentMode();
?>
<div id="tandym-magento-pdp-mapps">
<tandym-mapps data-tandym-widget='PDP' data-tandym-product-price='<?php echo $itemPrice ?>'></tandym-mapps>
</div>
<?php } ?>
