<?php
/*
 * @category    Tandym
 * @package     Tandym_Tandympay
 * @copyright   Copyright (c) Tandym (https://www.bytandym.com/)
 */
?>
<?php
use Tandym\Tandympay\Block\Widget\PDP;
/** @var $block PDP */
?>



<?php if ($block->isWidgetEnabledForPDP()) {?>
<?php 
$itemPrice = $block->getItemPrice() * 100;
$publicKey = $block->getPublicKey();
?>
<!-- <div id="tandym-magento-pdp-mapps"> -->
<script src="https://assets.platform.bytandym.com/mapps-assets/magento/tandym-mapps-magento-v1.js?tandym_api_key=<?php echo $publicKey; ?>" src_type="url"></script>

<tandym-mapps data-tandym-widget='PDP' data-tandym-product-price='<?php echo $itemPrice ?>'></tandym-mapps>

<!-- <div> -->
<?php } ?>
